version: "3"

services:
    web:
        build:
            context: ../
            dockerfile: deploy/Dockerfile
        ports:
            - "5050:5050"
        depends_on:
            - db
        restart: always
        environment:
            POSTGRES_DB: "{{postgres_database}}"
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST: db

    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: "{{postgres_database}}"
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
